name: Code Quality

on: [pull_request, push]

jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        #with:
        #  python-version: 3.10.13

      # Install poetry
      - name: Load cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-0
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Install dependencies
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      # Run tests
      - name: Run tests
        run: poetry run python -m unittest
